controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_page:
    path: /
    controller: App\Controller\PageController::index

add_video:
    path: /add_video
    controller: App\Controller\VideoController::addVideo

add_category:
    path: /page/category
    controller: App\Controller\CategoryController::addCategory